-- 建立 DMS 系統必要的資料表
-- 此腳本會建立基本的資料表結構

USE DMS;
GO

-- 建立 Schema（如果不存在）
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'RIS')
BEGIN
    EXEC('CREATE SCHEMA RIS');
END
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'DMS')
BEGIN
    EXEC('CREATE SCHEMA DMS');
END
GO

-- 建立 RIS.SHMT_SOURCE1 資料表
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SHMT_SOURCE1' AND schema_id = SCHEMA_ID('RIS'))
BEGIN
    CREATE TABLE RIS.SHMT_SOURCE1 (
        AC_DATE NVARCHAR(20) NOT NULL,
        EMP_NO NVARCHAR(10) NOT NULL,
        STK_CD NVARCHAR(10) NOT NULL,
        TYPE NVARCHAR(20) NOT NULL,
        SHMT_DATE NVARCHAR(10) NOT NULL,
        CHF_CHG_YN NVARCHAR(10) NULL,
        DES NVARCHAR(500) NULL,
        SHMT_ADDR NVARCHAR(150) NULL,
        SSRG_DATE NVARCHAR(10) NULL,
        STATUS NVARCHAR(1) NULL DEFAULT 'Y',
        STK_NAME NVARCHAR(20) NULL,
        CONSTRAINT PK_shmtsource1 PRIMARY KEY (AC_DATE, EMP_NO, STK_CD, TYPE, SHMT_DATE)
    );
    PRINT 'Table RIS.SHMT_SOURCE1 created successfully';
END
GO

-- 建立 RIS.SHMT_SOURCE4 資料表
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'SHMT_SOURCE4' AND schema_id = SCHEMA_ID('RIS'))
BEGIN
    CREATE TABLE RIS.SHMT_SOURCE4 (
        AC_DATE NVARCHAR(20) NOT NULL,
        EMP_NO NVARCHAR(10) NOT NULL,
        STK_CD NVARCHAR(10) NOT NULL,
        STK_NAME NVARCHAR(20) NULL,
        COMP_NAME NVARCHAR(100) NULL,
        TEL NVARCHAR(30) NULL,
        ADDR NVARCHAR(200) NULL,
        BROKER_NAME NVARCHAR(100) NULL,
        BROKER_TEL NVARCHAR(30) NULL,
        SPOKESMAN NVARCHAR(50) NULL,
        PRESIDENT NVARCHAR(50) NULL,
        CHAIRMAN NVARCHAR(50) NULL,
        ID_NO NVARCHAR(10) NULL,
        CONSTRAINT PK_shmtsource4 PRIMARY KEY (AC_DATE, EMP_NO, STK_CD)
    );
    PRINT 'Table RIS.SHMT_SOURCE4 created successfully';
END
GO

-- 建立 DMS.STOCK_BALANCE 資料表（簡化版，僅包含必要欄位）
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'STOCK_BALANCE' AND schema_id = SCHEMA_ID('DMS'))
BEGIN
    CREATE TABLE DMS.STOCK_BALANCE (
        ID NVARCHAR(20) NOT NULL,
        CONTRACT_SEQ NVARCHAR(3) NOT NULL,
        AC_DATE DATE NOT NULL,
        STOCK_NO NVARCHAR(12) NOT NULL,
        ASSET_TYPE NVARCHAR(1) NOT NULL DEFAULT '1',
        SHARES DECIMAL(20, 5) NULL DEFAULT 0,
        CURRENCY_NO NVARCHAR(3) NULL,
        IMP_DATE DATE NULL,
        IMP_ID NVARCHAR(50) NULL,
        CONSTRAINT PK_stockbalance PRIMARY KEY (ID, CONTRACT_SEQ, AC_DATE, STOCK_NO, ASSET_TYPE)
    );
    PRINT 'Table DMS.STOCK_BALANCE created successfully';
END
GO

PRINT 'All tables created successfully!';
GO

