-- 配息功能測試資料初始化腳本
USE DMS;
GO

-- 確保 SCHEMA 存在
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'MDS')
BEGIN
    EXEC('CREATE SCHEMA [MDS]')
END
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'NAV')
BEGIN
    EXEC('CREATE SCHEMA [NAV]')
END
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'FAS')
BEGIN
    EXEC('CREATE SCHEMA [FAS]')
END
GO

-- 建立 NAV.NAV 測試資料表（如果不存在）
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'NAV' AND schema_id = SCHEMA_ID('NAV'))
BEGIN
    CREATE TABLE NAV.NAV (
        FUND_NO VARCHAR(5) NOT NULL,
        NAV_DATE DATETIME2(0) NOT NULL,
        NAV DECIMAL(14, 8) NOT NULL,
        PRIMARY KEY (FUND_NO, NAV_DATE)
    )
END
GO

-- 建立 FAS.FUND_LEDGE 測試資料表（如果不存在）
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FUND_LEDGE' AND schema_id = SCHEMA_ID('FAS'))
BEGIN
    CREATE TABLE FAS.FUND_LEDGE (
        FUND_NO VARCHAR(5) NOT NULL,
        AC_DATE DATETIME2(0) NOT NULL,
        BAL_SHARE DECIMAL(20, 5) NOT NULL,
        PRIMARY KEY (FUND_NO, AC_DATE)
    )
END
GO

-- 建立 MDS.FUND_DIV_SET 測試資料表（如果不存在）
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FUND_DIV_SET' AND schema_id = SCHEMA_ID('MDS'))
BEGIN
    CREATE TABLE MDS.FUND_DIV_SET (
        FUND_NO VARCHAR(5) NOT NULL,
        DIV_TYPE VARCHAR(1) NOT NULL,
        ITEM01_SEQ INT NULL,
        ITEM02_SEQ INT NULL,
        ITEM03_SEQ INT NULL,
        ITEM04_SEQ INT NULL,
        ITEM05_SEQ INT NULL,
        ITEM06_SEQ INT NULL,
        ITEM07_SEQ INT NULL,
        ITEM08_SEQ INT NULL,
        ITEM09_SEQ INT NULL,
        ITEM10_SEQ INT NULL,
        CAPITAL_TYPE VARCHAR(1) NULL DEFAULT 'N',
        EMAIL_LIST VARCHAR(500) NULL,
        PRIMARY KEY (FUND_NO, DIV_TYPE)
    )
END
GO

-- 建立 MDS.FUND_DIV_OBJ 測試資料表（如果不存在）
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FUND_DIV_OBJ' AND schema_id = SCHEMA_ID('MDS'))
BEGIN
    CREATE TABLE MDS.FUND_DIV_OBJ (
        FUND_NO VARCHAR(5) NOT NULL,
        DIV_TYPE VARCHAR(1) NOT NULL,
        TX_DATE DATETIME2(0) NOT NULL,
        DIV_OBJ DECIMAL(8, 6) NULL,
        DIV_OBJ_AMT DECIMAL(12, 6) NULL,
        PRIMARY KEY (FUND_NO, DIV_TYPE, TX_DATE)
    )
END
GO

-- 建立 MDS.FUND_DIV 測試資料表（如果不存在）
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FUND_DIV' AND schema_id = SCHEMA_ID('MDS'))
BEGIN
    CREATE TABLE MDS.FUND_DIV (
        FUND_NO VARCHAR(5) NOT NULL,
        DIVIDEND_YEAR INT NULL,
        DIVIDEND_DATE DATETIME2(0) NOT NULL,
        DIVIDEND_TYPE VARCHAR(1) NOT NULL,
        NAV DECIMAL(14, 8) NULL,
        UNIT DECIMAL(20, 5) NULL,
        PRE_DIV1 DECIMAL(20, 5) NULL,
        PRE_DIV2 DECIMAL(20, 5) NULL,
        PRE_DIV3 DECIMAL(20, 5) NULL,
        PRE_DIV4 DECIMAL(20, 5) NULL,
        PRE_DIV5 DECIMAL(20, 5) NULL,
        DIV1 DECIMAL(20, 5) NULL,
        DIV2 DECIMAL(20, 5) NULL,
        DIV3 DECIMAL(20, 5) NULL,
        DIV4 DECIMAL(20, 5) NULL,
        DIV5 DECIMAL(20, 5) NULL,
        FEE DECIMAL(20, 5) NULL,
        DIV_TOT DECIMAL(20, 5) NULL,
        DIV_RATE DECIMAL(12, 10) NULL,
        DIV_RATE_M DECIMAL(12, 10) NULL,
        DIV_RATE_O DECIMAL(12, 10) NULL,
        CAPITAL_RATE DECIMAL(12, 10) NULL,
        CAPITAL_RATE_M DECIMAL(12, 10) NULL,
        FEE_RATE DECIMAL(12, 10) NULL,
        FEE_RATE_M DECIMAL(12, 10) NULL,
        DIV_OBJ DECIMAL(8, 6) NULL,
        DIV_PRE DECIMAL(8, 6) NULL,
        PRE_DIV1_RATE DECIMAL(12, 10) NULL,
        PRE_DIV1_RATE_M DECIMAL(12, 10) NULL,
        PRE_DIV2_RATE DECIMAL(12, 10) NULL,
        PRE_DIV2_RATE_M DECIMAL(12, 10) NULL,
        PRE_DIV3_RATE DECIMAL(12, 10) NULL,
        PRE_DIV3_RATE_M DECIMAL(12, 10) NULL,
        PRE_DIV4_RATE DECIMAL(12, 10) NULL,
        PRE_DIV4_RATE_M DECIMAL(12, 10) NULL,
        PRE_DIV5_RATE DECIMAL(12, 10) NULL,
        PRE_DIV5_RATE_M DECIMAL(12, 10) NULL,
        DIV1_RATE DECIMAL(12, 10) NULL,
        DIV1_RATE_M DECIMAL(12, 10) NULL,
        DIV2_RATE DECIMAL(12, 10) NULL,
        DIV2_RATE_M DECIMAL(12, 10) NULL,
        DIV3_RATE DECIMAL(12, 10) NULL,
        DIV3_RATE_M DECIMAL(12, 10) NULL,
        DIV4_RATE DECIMAL(12, 10) NULL,
        DIV4_RATE_M DECIMAL(12, 10) NULL,
        DIV5_RATE DECIMAL(12, 10) NULL,
        DIV5_RATE_M DECIMAL(12, 10) NULL,
        STEP1_STATUS VARCHAR(1) NULL,
        STEP2_STATUS VARCHAR(1) NULL,
        STEP3_STATUS VARCHAR(1) NULL,
        STEP2_COF_EMP VARCHAR(10) NULL,
        STEP2_COF_TIME DATETIME2(0) NULL,
        STEP3_COF_EMP VARCHAR(10) NULL,
        STEP3_COF_TIME DATETIME2(0) NULL,
        STATUS VARCHAR(1) NULL,
        STATUS_C VARCHAR(1) NULL,
        PRIMARY KEY (FUND_NO, DIVIDEND_DATE, DIVIDEND_TYPE)
    )
END
GO

-- 清除現有測試資料（可選）
-- DELETE FROM MDS.FUND_DIV WHERE FUND_NO IN ('A001', 'A002');
-- DELETE FROM MDS.FUND_DIV_SET WHERE FUND_NO IN ('A001', 'A002');
-- DELETE FROM MDS.FUND_DIV_OBJ WHERE FUND_NO IN ('A001', 'A002');
-- DELETE FROM NAV.NAV WHERE FUND_NO IN ('A001', 'A002');
-- DELETE FROM FAS.FUND_LEDGE WHERE FUND_NO IN ('A001', 'A002');
-- GO

-- 插入測試基金 NAV 資料
MERGE NAV.NAV AS target
USING (SELECT 'A001' AS FUND_NO, '2024-12-01' AS NAV_DATE, 10.5 AS NAV) AS source
ON (target.FUND_NO = source.FUND_NO AND target.NAV_DATE = source.NAV_DATE)
WHEN MATCHED THEN UPDATE SET NAV = source.NAV
WHEN NOT MATCHED THEN INSERT (FUND_NO, NAV_DATE, NAV) VALUES (source.FUND_NO, source.NAV_DATE, source.NAV);
GO

MERGE NAV.NAV AS target
USING (SELECT 'A002' AS FUND_NO, '2024-12-01' AS NAV_DATE, 15.8 AS NAV) AS source
ON (target.FUND_NO = source.FUND_NO AND target.NAV_DATE = source.NAV_DATE)
WHEN MATCHED THEN UPDATE SET NAV = source.NAV
WHEN NOT MATCHED THEN INSERT (FUND_NO, NAV_DATE, NAV) VALUES (source.FUND_NO, source.NAV_DATE, source.NAV);
GO

-- 插入測試基金單位數資料
MERGE FAS.FUND_LEDGE AS target
USING (SELECT 'A001' AS FUND_NO, '2024-12-01' AS AC_DATE, 1000000.0 AS BAL_SHARE) AS source
ON (target.FUND_NO = source.FUND_NO AND target.AC_DATE = source.AC_DATE)
WHEN MATCHED THEN UPDATE SET BAL_SHARE = source.BAL_SHARE
WHEN NOT MATCHED THEN INSERT (FUND_NO, AC_DATE, BAL_SHARE) VALUES (source.FUND_NO, source.AC_DATE, source.BAL_SHARE);
GO

MERGE FAS.FUND_LEDGE AS target
USING (SELECT 'A002' AS FUND_NO, '2024-12-01' AS AC_DATE, 2000000.0 AS BAL_SHARE) AS source
ON (target.FUND_NO = source.FUND_NO AND target.AC_DATE = source.AC_DATE)
WHEN MATCHED THEN UPDATE SET BAL_SHARE = source.BAL_SHARE
WHEN NOT MATCHED THEN INSERT (FUND_NO, AC_DATE, BAL_SHARE) VALUES (source.FUND_NO, source.AC_DATE, source.BAL_SHARE);
GO

-- 插入配息參數設定（月配）
MERGE MDS.FUND_DIV_SET AS target
USING (
    SELECT 'A001' AS FUND_NO, 'M' AS DIV_TYPE,
           1 AS ITEM01_SEQ, 2 AS ITEM02_SEQ, 3 AS ITEM03_SEQ, 4 AS ITEM04_SEQ, 5 AS ITEM05_SEQ,
           6 AS ITEM06_SEQ, 7 AS ITEM07_SEQ, 8 AS ITEM08_SEQ, 9 AS ITEM09_SEQ, 10 AS ITEM10_SEQ,
           'Y' AS CAPITAL_TYPE
) AS source
ON (target.FUND_NO = source.FUND_NO AND target.DIV_TYPE = source.DIV_TYPE)
WHEN MATCHED THEN UPDATE SET
    ITEM01_SEQ = source.ITEM01_SEQ, ITEM02_SEQ = source.ITEM02_SEQ, ITEM03_SEQ = source.ITEM03_SEQ,
    ITEM04_SEQ = source.ITEM04_SEQ, ITEM05_SEQ = source.ITEM05_SEQ, ITEM06_SEQ = source.ITEM06_SEQ,
    ITEM07_SEQ = source.ITEM07_SEQ, ITEM08_SEQ = source.ITEM08_SEQ, ITEM09_SEQ = source.ITEM09_SEQ,
    ITEM10_SEQ = source.ITEM10_SEQ, CAPITAL_TYPE = source.CAPITAL_TYPE
WHEN NOT MATCHED THEN INSERT (FUND_NO, DIV_TYPE, ITEM01_SEQ, ITEM02_SEQ, ITEM03_SEQ, ITEM04_SEQ, ITEM05_SEQ,
                               ITEM06_SEQ, ITEM07_SEQ, ITEM08_SEQ, ITEM09_SEQ, ITEM10_SEQ, CAPITAL_TYPE)
    VALUES (source.FUND_NO, source.DIV_TYPE, source.ITEM01_SEQ, source.ITEM02_SEQ, source.ITEM03_SEQ,
            source.ITEM04_SEQ, source.ITEM05_SEQ, source.ITEM06_SEQ, source.ITEM07_SEQ, source.ITEM08_SEQ,
            source.ITEM09_SEQ, source.ITEM10_SEQ, source.CAPITAL_TYPE);
GO

-- 插入目標配息率設定
MERGE MDS.FUND_DIV_OBJ AS target
USING (
    SELECT 'A001' AS FUND_NO, 'M' AS DIV_TYPE, '2024-01-01' AS TX_DATE,
           0.05 AS DIV_OBJ, NULL AS DIV_OBJ_AMT
) AS source
ON (target.FUND_NO = source.FUND_NO AND target.DIV_TYPE = source.DIV_TYPE AND target.TX_DATE = source.TX_DATE)
WHEN MATCHED THEN UPDATE SET DIV_OBJ = source.DIV_OBJ, DIV_OBJ_AMT = source.DIV_OBJ_AMT
WHEN NOT MATCHED THEN INSERT (FUND_NO, DIV_TYPE, TX_DATE, DIV_OBJ, DIV_OBJ_AMT)
    VALUES (source.FUND_NO, source.DIV_TYPE, source.TX_DATE, source.DIV_OBJ, source.DIV_OBJ_AMT);
GO

-- 插入測試配息資料（待確認狀態）
MERGE MDS.FUND_DIV AS target
USING (
    SELECT 'A001' AS FUND_NO, 2024 AS DIVIDEND_YEAR, '2024-12-01' AS DIVIDEND_DATE, 'M' AS DIVIDEND_TYPE,
           10.5 AS NAV, 1000000.0 AS UNIT,
           10000.0 AS PRE_DIV1, 5000.0 AS PRE_DIV2, 3000.0 AS PRE_DIV3, 2000.0 AS PRE_DIV4, 1000.0 AS PRE_DIV5,
           15000.0 AS DIV1, 8000.0 AS DIV2, 5000.0 AS DIV3, 3000.0 AS DIV4, 2000.0 AS DIV5,
           1000.0 AS FEE, 'C' AS STEP2_STATUS
) AS source
ON (target.FUND_NO = source.FUND_NO AND target.DIVIDEND_DATE = source.DIVIDEND_DATE AND target.DIVIDEND_TYPE = source.DIVIDEND_TYPE)
WHEN MATCHED THEN UPDATE SET
    NAV = source.NAV, UNIT = source.UNIT,
    PRE_DIV1 = source.PRE_DIV1, PRE_DIV2 = source.PRE_DIV2, PRE_DIV3 = source.PRE_DIV3,
    PRE_DIV4 = source.PRE_DIV4, PRE_DIV5 = source.PRE_DIV5,
    DIV1 = source.DIV1, DIV2 = source.DIV2, DIV3 = source.DIV3, DIV4 = source.DIV4, DIV5 = source.DIV5,
    FEE = source.FEE, STEP2_STATUS = source.STEP2_STATUS
WHEN NOT MATCHED THEN INSERT (FUND_NO, DIVIDEND_YEAR, DIVIDEND_DATE, DIVIDEND_TYPE, NAV, UNIT,
                               PRE_DIV1, PRE_DIV2, PRE_DIV3, PRE_DIV4, PRE_DIV5,
                               DIV1, DIV2, DIV3, DIV4, DIV5, FEE, STEP2_STATUS, STATUS, STATUS_C)
    VALUES (source.FUND_NO, source.DIVIDEND_YEAR, source.DIVIDEND_DATE, source.DIVIDEND_TYPE, source.NAV, source.UNIT,
            source.PRE_DIV1, source.PRE_DIV2, source.PRE_DIV3, source.PRE_DIV4, source.PRE_DIV5,
            source.DIV1, source.DIV2, source.DIV3, source.DIV4, source.DIV5, source.FEE, source.STEP2_STATUS, 'Y', 'N');
GO

PRINT '配息測試資料插入完成！';
PRINT '測試基金代號: A001 (月配)';
PRINT '配息基準日: 2024-12-01';
PRINT 'NAV: 10.5';
PRINT '單位數: 1,000,000';
PRINT '可分配收益: 60,000 (扣除費用後)';
GO
